project:
  type: website
  output-dir: docs

format:
  html:
    theme: none
    css: styles.css

execute:
  after:
    - cp .nojekyll docs/.nojekyll   # Copy .nojekyll after render

website:
  title: "Lina Arag√≥n"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About Me"
        href: about.qmd
      - text: "Research"
        href: research.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Outreach"
        href: outreach.qmd
      - text: "Fieldwork"
        href: fieldwork.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Resume (CV)"
        href: resume.qmd
      - text: "Get in touch!"
        href: contact.qmd

